sudo: required
services:
  - docker

before_install:
  - docker build -t klaudiuszkudla/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true klaudiuszkudla/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-851725555123"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"